export const SHOWSIDEBAR = 'SHOWSIDEBAR';
export const HIDESIDEBAR = 'HIDESIDEBAR';
export const SHOWSEARCH = "SHOWSEARCH ";
export const HIDESEARCH = "HIDESEARCH";
export const ONVIDEOSELECT = "ONVIDEOSELECT";